### ISSUE TITLE
How to use different cell types

### ISSUE THREAD

**Issue by rawnly** [CombineCommunity/CombineDataSources#9]
Hi! I need to display different cells in the same section.. right now I have a `renderCell(cellType: CellType, indexPath: IndexPath)` method, where `CellType` is a custom `enum` to differentiate the type of cell.

Is it possible to archive the same result trough the `tableView.sectionsSubscriber` method?

**Comment by icanzilb** [comment]
This should give you enough info to find a solution: http://trycombine.com/posts/combinedatasources-multiple-sections/
